Repository hauler-dev/hauler-helm, pull requests merged in 2025-02, with the labels that each got.

#12 updated default values and defaulted tls false
  charts/hauler/values.yaml
Labels: bug, enhancement

#13 added support for labels/annotations
  charts/hauler/templates/hauler-fileserver/hauler-fileserver-deployment.yaml
  charts/hauler/templates/hauler-fileserver/hauler-fileserver-ingress.yaml
  charts/hauler/templates/hauler-fileserver/hauler-fileserver-service.yaml
  charts/hauler/templates/hauler-registry/hauler-registry-deployment.yaml
  charts/hauler/templates/hauler-registry/hauler-registry-ingress.yaml
  charts/hauler/templates/hauler-registry/hauler-registry-service.yaml
  charts/hauler/templates/hauler/hauler-jobs.yaml
  charts/hauler/templates/hauler/hauler-pvc.yaml
  charts/hauler/templates/hauler/hauler-rbac.yaml
  charts/hauler/values.yaml
Labels: enhancement

#15 updates for `v1.2.0`
  charts/hauler/Chart.yaml
  charts/hauler/README.md
  charts/hauler/app-readme.md
  charts/hauler/templates/hauler/hauler-debug.yaml
  charts/hauler/templates/hauler/hauler-jobs.yaml
  charts/hauler/values.yaml
Labels: enhancement

#16 updates for v1.2.1
  charts/hauler/Chart.yaml
  charts/hauler/README.md
  charts/hauler/app-readme.md
  charts/hauler/values.yaml
Labels: documentation, enhancement

#27 Add health checks and tests (#13)
  .github/workflows/release.yaml
  .github/workflows/tests.yaml
  README.md
  charts/hauler/Chart.yaml
  charts/hauler/README.md
  charts/hauler/app-readme.md
  charts/hauler/ci/README.md
  charts/hauler/ci/all-local-values.yaml
  charts/hauler/ci/all-remote-values.yaml
  charts/hauler/ci/expected/all-local-reg-output.txt
  charts/hauler/ci/expected/all-local-web-output.txt
  charts/hauler/ci/expected/all-remote-reg-output.txt
  charts/hauler/ci/expected/all-remote-web-output.txt
  charts/hauler/ci/expected/kitchsink-reg-output.txt
  charts/hauler/ci/expected/kitchsink-web-output.txt
  charts/hauler/ci/expected/local-hauls-reg-output.txt
  charts/hauler/ci/expected/local-hauls-web-output.txt
  charts/hauler/ci/expected/local-manifests-reg-output.txt
  charts/hauler/ci/expected/local-manifests-web-output.txt
  charts/hauler/ci/expected/remote-hauls-reg-output.txt
  charts/hauler/ci/expected/remote-hauls-web-output.txt
  charts/hauler/ci/expected/remote-manifests-reg-output.txt
  charts/hauler/ci/expected/remote-manifests-web-output.txt
  charts/hauler/ci/expected/store-reg-output.txt
  charts/hauler/ci/expected/store-web-output.txt
  charts/hauler/ci/kitchsink-values.yaml
  charts/hauler/ci/local-hauls-values.yaml
  charts/hauler/ci/local-manifests-values.yaml
  charts/hauler/ci/remote-hauls-values.yaml
  charts/hauler/ci/remote-manifests-values.yaml
  charts/hauler/ci/store-manifest.yaml
  charts/hauler/ci/store-values.yaml
  charts/hauler/ci/test-maker.sh
  charts/hauler/ci/test-manifest.yaml
  charts/hauler/ci/test-manifest2.yaml
  charts/hauler/ci/test-pod.yaml
  charts/hauler/templates/hauler-fileserver/hauler-fileserver-deployment.yaml
  charts/hauler/templates/hauler-registry/hauler-registry-deployment.yaml
  charts/hauler/templates/hauler/hauler-jobs.yaml
  charts/hauler/values.yaml
  ct.yaml
Labels: enhancement
